In [80]:
import pandas as pd

from ast import literal_eval

from tqdm import tqdm
tqdm.pandas()

import urlexpander

# Twitter

In [6]:
TWITTER_LOCS = [f'../../data/twitter_data/tweets_batch{i}.csv' for i in range(1, 4)]

In [8]:
dfs = [pd.read_csv(loc) for loc in TWITTER_LOCS]

C:\Users\ndeas\miniconda3\lib\site-packages\ipykernel_launcher.py:1: DtypeWarning: Columns (20,21,22,23,24,25,26,31,32,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,200,201,203,204,206,207,209,210) have mixed types.Specify dtype option on import or set low_memory=False.
  """Entry point for launching an IPython kernel.
C:\Users\ndeas\miniconda3\lib\site-packages\ipykernel_launcher.py:1: DtypeWarning: Columns (20,21,22,23,24,28,29,55,56,57,58,59,60,197,198,200,201,203,204,206,207,209,210) have mixed types.Specify dtype option on import or set low_memory=False.
  """Entry point for launching an IPython kernel.
C:\Users\ndeas\miniconda3\lib\site-packages\ipykernel_launcher.py:1: DtypeWarning: Columns (13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,145,146,148,149,151,152,154,155,157,158,160,161,163,164,166,167,169,170,172,173,175,176,178,179,181,182,184,185,187,188,190,191,193,194,196,197,199,200,202,203,205,206,208,209,211,212,214,215,217,218,220,221,223,224,226,227,229,230,232,233,235,236,238,239,241,242,244,245,247,248,250,251) have mixed types.Specify dtype option on import or set low_memory=False.
  """Entry point for launching an IPython kernel.

In [9]:
all_tweets = pd.concat(dfs, axis = 0)

In [11]:
all_tweets.to_csv('../../data/twitter_data/all_tweets.csv', index = None)

In [22]:
list(all_tweets.columns)

['conversation_id',
 'created_at',
 'favorite_count',
 'full_text',
 'hashtags/0',
 'hashtags/1',
 'hashtags/2',
 'hashtags/3',
 'hashtags/4',
 'hashtags/5',
 'hashtags/6',
 'hashtags/7',
 'hashtags/8',
 'hashtags/9',
 'hashtags/10',
 'hashtags/11',
 'hashtags/12',
 'hashtags/13',
 'hashtags/14',
 'hashtags/15',
 'hashtags/16',
 'hashtags/17',
 'hashtags/18',
 'hashtags/19',
 'hashtags/20',
 'hashtags/21',
 'hashtags/22',
 'id',
 'reply_count',
 'retweet_count',
 'symbols/0',
 'symbols/1',
 'symbols/2',
 'url',
 'urls/0/display_url',
 'urls/0/expanded_url',
 'urls/0/url',
 'urls/1/display_url',
 'urls/1/expanded_url',
 'urls/1/url',
 'urls/2/display_url',
 'urls/2/expanded_url',
 'urls/2/url',
 'urls/3/display_url',
 'urls/3/expanded_url',
 'urls/3/url',
 'urls/4/display_url',
 'urls/4/expanded_url',
 'urls/4/url',
 'urls/5/display_url',
 'urls/5/expanded_url',
 'urls/5/url',
 'urls/6/display_url',
 'urls/6/expanded_url',
 'urls/6/url',
 'urls/7/display_url',
 'urls/7/expanded_url',
 'urls/7/url',
 'urls/8/display_url',
 'urls/8/expanded_url',
 'urls/8/url',
 'urls/9/display_url',
 'urls/9/expanded_url',
 'urls/9/url',
 'user_mentions/0/id_str',
 'user_mentions/0/name',
 'user_mentions/0/screen_name',
 'user_mentions/1/id_str',
 'user_mentions/1/name',
 'user_mentions/1/screen_name',
 'user_mentions/2/id_str',
 'user_mentions/2/name',
 'user_mentions/2/screen_name',
 'user_mentions/3/id_str',
 'user_mentions/3/name',
 'user_mentions/3/screen_name',
 'user_mentions/4/id_str',
 'user_mentions/4/name',
 'user_mentions/4/screen_name',
 'user_mentions/5/id_str',
 'user_mentions/5/name',
 'user_mentions/5/screen_name',
 'user_mentions/6/id_str',
 'user_mentions/6/name',
 'user_mentions/6/screen_name',
 'user_mentions/7/id_str',
 'user_mentions/7/name',
 'user_mentions/7/screen_name',
 'user_mentions/8/id_str',
 'user_mentions/8/name',
 'user_mentions/8/screen_name',
 'user_mentions/9/id_str',
 'user_mentions/9/name',
 'user_mentions/9/screen_name',
 'user_mentions/10/id_str',
 'user_mentions/10/name',
 'user_mentions/10/screen_name',
 'user_mentions/11/id_str',
 'user_mentions/11/name',
 'user_mentions/11/screen_name',
 'user_mentions/12/id_str',
 'user_mentions/12/name',
 'user_mentions/12/screen_name',
 'user_mentions/13/id_str',
 'user_mentions/13/name',
 'user_mentions/13/screen_name',
 'user_mentions/14/id_str',
 'user_mentions/14/name',
 'user_mentions/14/screen_name',
 'user_mentions/15/id_str',
 'user_mentions/15/name',
 'user_mentions/15/screen_name',
 'user_mentions/16/id_str',
 'user_mentions/16/name',
 'user_mentions/16/screen_name',
 'user_mentions/17/id_str',
 'user_mentions/17/name',
 'user_mentions/17/screen_name',
 'user_mentions/18/id_str',
 'user_mentions/18/name',
 'user_mentions/18/screen_name',
 'user_mentions/19/id_str',
 'user_mentions/19/name',
 'user_mentions/19/screen_name',
 'user_mentions/20/id_str',
 'user_mentions/20/name',
 'user_mentions/20/screen_name',
 'user_mentions/21/id_str',
 'user_mentions/21/name',
 'user_mentions/21/screen_name',
 'user_mentions/22/id_str',
 'user_mentions/22/name',
 'user_mentions/22/screen_name',
 'user_mentions/23/id_str',
 'user_mentions/23/name',
 'user_mentions/23/screen_name',
 'user_mentions/24/id_str',
 'user_mentions/24/name',
 'user_mentions/24/screen_name',
 'user_mentions/25/id_str',
 'user_mentions/25/name',
 'user_mentions/25/screen_name',
 'user_mentions/26/id_str',
 'user_mentions/26/name',
 'user_mentions/26/screen_name',
 'user_mentions/27/id_str',
 'user_mentions/27/name',
 'user_mentions/27/screen_name',
 'user_mentions/28/id_str',
 'user_mentions/28/name',
 'user_mentions/28/screen_name',
 'user_mentions/29/id_str',
 'user_mentions/29/name',
 'user_mentions/29/screen_name',
 'user_mentions/30/id_str',
 'user_mentions/30/name',
 'user_mentions/30/screen_name',
 'user_mentions/31/id_str',
 'user_mentions/31/name',
 'user_mentions/31/screen_name',
 'user_mentions/32/id_str',
 'user_mentions/32/name',
 'user_mentions/32/screen_name',
 'user_mentions/33/id_str',
 'user_mentions/33/name',
 'user_mentions/33/screen_name',
 'user_mentions/34/id_str',
 'user_mentions/34/name',
 'user_mentions/34/screen_name',
 'user_mentions/35/id_str',
 'user_mentions/35/name',
 'user_mentions/35/screen_name',
 'user_mentions/36/id_str',
 'user_mentions/36/name',
 'user_mentions/36/screen_name',
 'user_mentions/37/id_str',
 'user_mentions/37/name',
 'user_mentions/37/screen_name',
 'user_mentions/38/id_str',
 'user_mentions/38/name',
 'user_mentions/38/screen_name',
 'user_mentions/39/id_str',
 'user_mentions/39/name',
 'user_mentions/39/screen_name',
 'user_mentions/40/id_str',
 'user_mentions/40/name',
 'user_mentions/40/screen_name',
 'user_mentions/41/id_str',
 'user_mentions/41/name',
 'user_mentions/41/screen_name',
 'user_mentions/42/id_str',
 'user_mentions/42/name',
 'user_mentions/42/screen_name',
 'user_mentions/43/id_str',
 'user_mentions/43/name',
 'user_mentions/43/screen_name',
 'user_mentions/44/id_str',
 'user_mentions/44/name',
 'user_mentions/44/screen_name',
 'user_mentions/45/id_str',
 'user_mentions/45/name',
 'user_mentions/45/screen_name',
 'user_mentions/46/id_str',
 'user_mentions/46/name',
 'user_mentions/46/screen_name',
 'user_mentions/47/id_str',
 'user_mentions/47/name',
 'user_mentions/47/screen_name',
 'user_mentions/48/id_str',
 'user_mentions/48/name',
 'user_mentions/48/screen_name',
 'user_mentions/49/id_str',
 'user_mentions/49/name',
 'user_mentions/49/screen_name',
 'hashtags/23',
 'hashtags/24',
 'hashtags/25',
 'hashtags/26',
 'symbols/3',
 'symbols/4',
 'symbols/5',
 'symbols/6',
 'symbols/7',
 'symbols/8',
 'symbols/9',
 'symbols/10',
 'symbols/11',
 'symbols/12',
 'symbols/13',
 'symbols/14',
 'symbols/15',
 'symbols/16',
 'symbols/17',
 'symbols/18',
 'symbols/19',
 'symbols/20',
 'symbols/21',
 'symbols/22',
 'symbols/23',
 'symbols/24',
 'symbols/25',
 'symbols/26',
 'symbols/27',
 'symbols/28',
 'symbols/29',
 'symbols/30',
 'symbols/31',
 'symbols/32',
 'symbols/33',
 'symbols/34',
 'symbols/35',
 'symbols/36']

In [21]:
all_tweets

,conversation_id,created_at,favorite_count,full_text,hashtags/0,hashtags/1,hashtags/2,hashtags/3,hashtags/4,hashtags/5,...,symbols/27,symbols/28,symbols/29,symbols/30,symbols/31,symbols/32,symbols/33,symbols/34,symbols/35,symbols/36
0,1240675964763492354,2020-03-19T16:26:15.000Z,4,Mnuchin: Family of 4 could get $3K under virus...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1240688569452081152,2020-03-19T17:16:20.000Z,0,WASHINGTON (AP) — The first federal checks to ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1240696232906911747,2020-03-19T17:46:47.000Z,1,@tonetalks @BreakingBrown @JacksonLeeTX18 @Joe...,ADOS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1240956149328904192,2020-03-20T10:59:36.000Z,0,"When thing are better, is this paid back? If n...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1240767510972190722,2020-03-19T22:30:01.000Z,0,https://t.co/9iOGn23ozM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103983,1353921579516878849,2021-01-26T04:23:53.000Z,0,McConnell folded! Senate Republican leader McC...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103984,1084260118055841792,2019-01-13T02:36:18.000Z,4,"@nycsouthpaw Lots of questions, like why are w...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103985,1262820353245618178,2020-05-19T19:00:08.000Z,0,"Keep in mind, when these tactics have been use...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103986,1101983242687823873,2019-03-02T23:10:53.000Z,12,In case u missed it. ➡️ F.B.I. Opened Inquiry ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103987,1465718796547764227,2021-11-30T16:26:07.000Z,20,"""While our existing policies and Twitter Rules...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
cols = ['full_text', 'created_at', 'url']
cols += [f'urls/{i}/expanded_url' for i in range(10)]
tweets_short = all_tweets[cols]

In [25]:
tweets_short

,full_text,created_at,url,urls/0/expanded_url,urls/1/expanded_url,urls/2/expanded_url,urls/3/expanded_url,urls/4/expanded_url,urls/5/expanded_url,urls/6/expanded_url,urls/7/expanded_url,urls/8/expanded_url,urls/9/expanded_url
0,Mnuchin: Family of 4 could get $3K under virus...,2020-03-19T16:26:15.000Z,https://twitter.com/ZekeJMiller/status/1240675...,https://apnews.com/0373a78b0aacc49d1f6bd8901c8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,WASHINGTON (AP) — The first federal checks to ...,2020-03-19T17:16:20.000Z,https://twitter.com/Mutwiba/status/12406885694...,https://apnews.com/0373a78b0aacc49d1f6bd8901c8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,@tonetalks @BreakingBrown @JacksonLeeTX18 @Joe...,2020-03-19T17:46:47.000Z,https://twitter.com/waiters_rashawn/status/124...,https://apnews.com/0373a78b0aacc49d1f6bd8901c8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"When thing are better, is this paid back? If n...",2020-03-20T10:59:36.000Z,https://twitter.com/SocialistProg/status/12409...,https://apnews.com/0373a78b0aacc49d1f6bd8901c8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://t.co/9iOGn23ozM,2020-03-19T22:30:01.000Z,https://twitter.com/theinsidedrop/status/12407...,https://apnews.com/0373a78b0aacc49d1f6bd8901c8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103983,McConnell folded! Senate Republican leader McC...,2021-01-26T04:23:53.000Z,https://twitter.com/Cathey_Thomas/status/13539...,https://reut.rs/3cfDSOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103984,"@nycsouthpaw Lots of questions, like why are w...",2019-01-13T02:36:18.000Z,https://twitter.com/salRides/status/1084277930...,https://www.nytimes.com/2019/01/11/us/politics...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103985,"Keep in mind, when these tactics have been use...",2020-05-19T19:00:08.000Z,https://twitter.com/jacadisjacadat/status/1262...,http://www.lawfareblog.com/flynn-redux-what-th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103986,In case u missed it. ➡️ F.B.I. Opened Inquiry ...,2019-03-02T23:10:53.000Z,https://twitter.com/flwrpwr1969/status/1101983...,https://www.nytimes.com/2019/01/11/us/politics...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103987,"""While our existing policies and Twitter Rules...",2021-11-30T16:26:07.000Z,https://twitter.com/0rf/status/146571879654776...,https://blog.twitter.com/en_us/topics/company/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
tweets_short.to_csv('../../data/data_clean/tweets_clean.csv', index = None)

# Reddit

In [14]:
all_redd = pd.read_csv('../../data/reddit_data/reddit_scrape.csv', on_bad_lines = 'skip')

C:\Users\ndeas\miniconda3\lib\site-packages\IPython\core\interactiveshell.py:3343: DtypeWarning: Columns (15,16,23,24,25,26,27,29,30,36,39,40,42,46,49,51,56,57,58,61,67,73) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [113]:
redd_short = all_redd[['id', 'title_q', 'date_q', 'title', 'selftext', 'url', 'url_overridden_by_dest', 'created']]

In [114]:
redd_short.to_csv('../../data/data_clean/reddit_clean.csv', index = None)

In [115]:
num_redd = redd_short.groupby('title_q').count()['id'].reset_index()

In [124]:
num_redd = num_redd.rename({'id': 'num_redd'}, axis = 1)

In [125]:
num_redd

                            title_q  num_redd
0    Britain Approves COVID Vaccine         2
1                Checks In The Mail         2
2     Impeachment Hearings Continue         3
3                         Inflation        42
4                      Judy Shelton        17
..                              ...       ...
698     Withdrawal from Afghanistan        21
699                      Xi Jinping         7
700                           Yemen        37
701           Yovanovitch Testifies        12
702            ‘Public Charge’ Rule        29

[703 rows x 2 columns]

# Twitter Mapping

In [151]:
TWITTER_FP = '../../data/data_clean/tweets_clean.csv'

In [152]:
tweets = pd.read_csv(TWITTER_FP)

C:\Users\ndeas\miniconda3\lib\site-packages\IPython\core\interactiveshell.py:3343: DtypeWarning: Columns (9,10,11,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [153]:
titles_news = flipside[['title', 'first_news_real']]

In [154]:
titles_news['first_news_real'] = titles_news['first_news_real'].apply(literal_eval)

C:\Users\ndeas\miniconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [155]:
title_map = {news: title for title, newslist in zip(titles_news['title'].values, titles_news['first_news_real'].values) for news in newslist}

In [156]:
title_map = {(key[:key.find('?')] if '?' in key else key) :val for key, val in title_map.items()}

In [157]:
def get_orig_title(row):
    url_cols = [f'urls/{i}/expanded_url' for i in range(10)]
    row_urls = row[url_cols].dropna().values
    row_urls = [(url[:url.find('?')] if '?' in url else url) for url in row_urls]
    
    for url in row_urls:
        if url in title_map.keys():
            return title_map[url]
    
    return None

In [159]:
tweets['title'] = tweets.progress_apply(get_orig_title, axis = 1)

100%|████████████████████████████████████████████████████████████████████████| 138297/138297 [01:04<00:00, 2137.30it/s]

In [160]:
tweets['title'] = tweets['title'].fillna(method = 'bfill')

In [161]:
tweets.to_csv('../../data/data_clean/tweets_w_title.csv', index = None)

In [102]:
num_tweets = tweets.groupby('title').count()

In [105]:
num_tweets = num_tweets['full_text']

In [108]:
num_tweets = num_tweets.reset_index()

In [123]:
num_tweets = num_tweets.rename({'full_text': 'num_tweets'}, axis = 1)

# Consolidate

In [185]:
TWITTER_FP = '../../data/data_clean/tweets_w_title.csv'
REDDIT_FP = '../../data/data_clean/reddit_clean.csv'
FLIPSIDE_FP = '../../data/webpage_data/full_flipside_data_proc.csv'

In [273]:
tweets = pd.read_csv(TWITTER_FP)
reddit = pd.read_csv(REDDIT_FP)
flipside = pd.read_csv(FLIPSIDE_FP)

In [261]:
flipside['title'] = flipside['title'].str.strip()
num_tweets['title'] = num_tweets['title'].str.strip()
num_redd['src_title'] = num_redd['src_title'].str.strip()

In [263]:
flipside_num = pd.merge(flipside, num_tweets, left_on = 'title', right_on = 'title', how = 'left')
flipside_num = pd.merge(flipside_num, num_redd, left_on = 'title', right_on = 'src_title', how = 'left')

In [264]:
flipside_num = flipside_num.drop('src_title', axis = 1)
flipside_num['num_tweets'] = flipside_num['num_tweets'].fillna(0)
flipside_num['num_redd'] = flipside_num['num_redd'].fillna(0)

In [265]:
flipside_num['tot_sm'] = flipside_num['num_tweets'] + flipside_num['num_redd']

In [266]:
flipside_num = flipside_num[flipside_num['tot_sm'] != 0]

In [267]:
flipside_num.to_csv('../../data/data_clean/flipside_w_meta.csv', index = None)

In [274]:
reddit = reddit.rename({'title_q': 'src_title', 'created': 'datetime'}, axis = 1)
reddit = reddit[['id', 'src_title', 'title', 'selftext', 'datetime']]
reddit['text'] = reddit['title'].fillna('') + '. ' + reddit['selftext'].fillna('')
reddit['sm_src'] = 'reddit'
reddit['datetime'] = pd.to_datetime(reddit['datetime'], unit = 's')
reddit = reddit.drop(['title', 'selftext'], axis = 1)

In [275]:
redd_groups = []
for i, group in reddit.groupby('src_title'):
    redd_groups.append(group.sample(20 if len(group) > 20 else len(group)))

In [277]:
reddit = pd.concat(redd_groups, axis = 0)

In [278]:
num_redd = reddit.groupby('src_title').count()['id'].reset_index()

In [279]:
num_redd = num_redd.rename({'id': 'num_redd'}, axis = 1)

In [280]:
num_redd

                           src_title  num_redd
0     Britain Approves COVID Vaccine         2
1                 Checks In The Mail         2
2      Impeachment Hearings Continue         3
3                          Inflation        20
4                       Judy Shelton        17
..                               ...       ...
698      Withdrawal from Afghanistan        20
699                       Xi Jinping         7
700                            Yemen        20
701            Yovanovitch Testifies        12
702             ‘Public Charge’ Rule        20

[703 rows x 2 columns]

In [281]:
reddit.to_csv('../../data/data_clean/reddit_w_meta.csv', index = None)

In [187]:
tweets = tweets.reset_index()
tweets = tweets[['index', 'title', 'created_at', 'full_text']]
tweets = tweets.rename({'index': 'id', 'title': 'src_title', 'full_text': 'text', 'created_at':'datetime'}, axis = 1)
tweets['sm_src'] = 'twitter'
tweets['datetime'] = pd.to_datetime(tweets['datetime'])

In [205]:
tweets.to_csv('../../data/data_clean/tweets_w_meta.csv', index = None)

In [283]:
all_sm = pd.concat((tweets, reddit), axis = 0)

In [284]:
all_sm.to_csv('../../data/data_clean/all_source.csv', index = None)

In [300]:
all_sm_groups = all_sm[['src_title', 'sm_src', 'text']]

In [301]:
all_sm_groups = all_sm_groups.groupby(['src_title', 'sm_src'])['text'].apply(lambda x: '|'.join(x)).reset_index()

In [302]:
all_sm_groups.to_csv('../../data/data_clean/all_source_concat.csv')

# Dataset Statistics

In [324]:
flipside_num = pd.read_csv('../../data/data_clean/flipside_w_meta.csv')
all_sm_groups = pd.read_csv('../../data/data_clean/all_source_concat.csv')

In [325]:
flipside_num.head(2)

,article_url,date,title,left_sum,right_sum,linked_arts,news_list,num_news,first_news_list,first_news_real,num_tweets,num_redd,tot_sm
0,https:/theflipside.io/archives/checks-in-the-mail,"March 20, 2020",Checks In The Mail,The left supports cash payments and argues tha...,The right is generally supportive of helping c...,['https://apnews.com/0373a78b0aacc49d1f6bd8901...,['https://apnews.com/0373a78b0aacc49d1f6bd8901...,13,['https://apnews.com/0373a78b0aacc49d1f6bd8901...,['https://apnews.com/0373a78b0aacc49d1f6bd8901...,223.0,2.0,225.0
1,https:/theflipside.io/archives/eos-regarding-t...,"January 26, 2021",EOs Regarding Transgender Rights,The left is supportive of both policies.,The right is critical of both policies.,['https://apnews.com/article/biden-reverse-ban...,['https://apnews.com/article/biden-reverse-ban...,24,['https://apnews.com/article/biden-reverse-ban...,['https://apnews.com/article/biden-reverse-ban...,168.0,0.0,168.0

In [ ]:
flipside_ref = flipside_num[~flipside_num['left_sum'].isna()]
reddit_texts = all_sm_groups[all_sm_groups['sm_src'] == 'reddit']
tweet_texts  = all_sm_groups[all_sm_groups['sm_src'] == 'twitter']
all_texts    = all_sm_groups.groupby('src_title')['text'].apply(lambda x: '||'.join(x)).reset_index()

reddit_texts['splits']  = reddit_texts["text"].str.split(r"[\.\!\?\\\-\|]")
reddit_texts['splits']  = reddit_texts["splits"].apply(lambda l: [t for t in l if len(t) > 5])
reddit_texts['num_sents'] = reddit_texts['splits'].apply(len)
reddit_texts['avg_len'] = reddit_texts['splits'].apply(lambda l: sum([len(sent.split(' ')) for sent in l])/len(l))

tweet_texts['splits']  = tweet_texts["text"].str.split(r"[\.\!\?\\\-\|]")
tweet_texts['splits']  = tweet_texts["splits"].apply(lambda l: [t for t in l if len(t) > 5])
tweet_texts['num_sents'] = tweet_texts['splits'].apply(len)
tweet_texts['avg_len'] = tweet_texts['splits'].apply(lambda l: sum([len(sent.split(' ')) for sent in l])/len(l))

all_texts['splits']  = all_texts["text"].str.split(r"[\.\!\?\\\-\|]")
all_texts['splits']  = all_texts["splits"].apply(lambda l: [t for t in l if len(t) > 5])
all_texts['num_sents'] = all_texts['splits'].apply(len)
all_texts['avg_len'] = all_texts['splits'].apply(lambda l: sum([len(sent.split(' ')) for sent in l])/len(l))

In [354]:
print(f'Total Articles: {len(all_sm_groups["src_title"].unique())}')
print(f'# References:   {len(flipside_ref)}')
print(f'Avg. LS Len:    {flipside_ref["left_sum"].str.len().mean():.3f}')
print(f'Avg. RS Len:    {flipside_ref["right_sum"].str.len().mean():.3f}')
print(f'Avg. Num R:     {reddit_texts["num_sents"].mean():.3f}')
print(f'Avg. Num T:     {tweet_texts["num_sents"].mean():.3f}')
print(f'Avg. Len R:     {reddit_texts["avg_len"].mean():.3f}')
print(f'Avg. Len T:     {tweet_texts["avg_len"].mean():.3f}')
print(f'Avg. Num Sent: {all_texts["num_sents"].mean(): .3f}')
print(f'Avg. Len Total: {all_texts["avg_len"].mean():.3f}')

Total Articles: 846
# References:   771
Avg. LS Len:    107.383
Avg. RS Len:    106.652
Avg. Num R:     50.242
Avg. Num T:     592.767
Avg. Len R:     9.891
Avg. Len T:     6.863
Avg. Num Sent:  628.911
Avg. Len Total: 6.989

# Final Dataset

In [381]:
flipside_f = flipside_num.drop(['first_news_list', 'first_news_real'], axis = 1)

In [382]:
tweets_merge = tweet_texts[['src_title', 'text']]
tweets_merge['src_title'] = tweets_merge['src_title'].str.strip()
flipside_f = pd.merge(flipside_f, tweets_merge, left_on = 'title', right_on = 'src_title', how = 'left').drop('src_title', axis = 1)
flipside_f = flipside_f.rename({'text': 'tweet_text'}, axis = 1)

C:\Users\ndeas\miniconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [383]:
reddit_merge = reddit_texts[['src_title', 'text']]
reddit_merge['src_title'] = reddit_merge['src_title'].str.strip()
flipside_f = pd.merge(flipside_f, reddit_merge, left_on = 'title', right_on = 'src_title', how = 'left').drop('src_title', axis = 1)
flipside_f = flipside_f.rename({'text': 'reddit_text'}, axis = 1)

C:\Users\ndeas\miniconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [384]:
flipside_f['reddit_text'] = flipside_f['reddit_text'].fillna('')
flipside_f['tweet_text'] = flipside_f['tweet_text'].fillna('')

In [387]:
flipside_f['all_texts'] = flipside_f['tweet_text'] + '|||' + flipside_f['reddit_text']

In [388]:
flipside_f.to_csv('../../data/data_clean/polisumm_final.csv', index = None)